project:
  type: website

website:
  title: "GLM 2026"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - lectures.qmd
      - homework.qmd
      - syllabus.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

